### ISSUE TITLE
The synthetic formulation of non-i.i.d. client data

### ISSUE THREAD

**Issue by MakingL** [epfml/federated-learning-public-code#2]
Hi, I have a question  about the method of synthesizing of non-i.i.d. client data in section C.2 that with corresponding code at [build_non_iid_by_dirichlet function](https://github.com/epfml/federated-learning-public-code/blob/9ec5432f4b7ba17b110ff39e84c30cecfca50568/codes/FedDF-code/pcode/datasets/partition_data.py#L197). Hope you can answer it for me.

As the [build_non_iid_by_dirichlet function](https://github.com/epfml/federated-learning-public-code/blob/9ec5432f4b7ba17b110ff39e84c30cecfca50568/codes/FedDF-code/pcode/datasets/partition_data.py#L197) shows, the clients are divided into groups for every 10, correspondingly, the data is divided into small patitions, and then the data in each patition is dispatched to client according to dirichlect distribution function. However, I did not find this detailed explanation in the paper, and I canot understand this implementation. Why not divide the input data to each client directly through the dirichlet distribution? Are there any advantage of the data division method shown in the code? 

Thank you!

**Comment by tlin-taolin** [comment]
Hi, thank you for your question.

Indeed `n_auxi_workers` is used to speed up the sampling procedure, otherwise, when we have a large number of `workers` and a low `non_iid_alpha` value, it will take quite a long time to return a reasonable good sampling result (though the condition in line 239 is quite weak).

You may set `n_auxi_workers` to the value of `n_workers`. Hope it helps.

**Comment by MakingL** [comment]
OK, thank you very much for your reply. I experimented with the scene you said, and it is exactly what you said. Now I see it more clearly. Thanks!

**Comment by WOWNICE** [comment]
> Hi, thank you for your question.
> 
> Indeed `n_auxi_workers` is used to speed up the sampling procedure, otherwise, when we have a large number of `workers` and a low `non_iid_alpha` value, it will take quite a long time to return a reasonable good sampling result (though the condition in line 239 is quite weak).
> 
> You may set `n_auxi_workers` to the value of `n_workers`. Hope it helps.

This is interesting. So you add an additional condition to make sure each client gets a reasonable amount of data?

Now I can see why my sampling result leads to some of the clients have only 1 or 2 samples. 

Thanks a lot!
