### ISSUE TITLE
Some Question About Build The Image

### ISSUE THREAD

**Issue by LazWorm** [epfml/federated-learning-public-code#3]
First of all, Your paper and your idea is so brilliant.
But Still So many questions when I tried to build your image 'pytorch-mpi'
1, Why apt-get install open-jdk-7(and many other software packages), Do we really need jdk in this project?
2, Why git clone pytorch source code (and vision, text ...) rather than use conda install pytorch, When compile, It give me so many ERROR, and of course, Failed.
Sorry, I'm a FL rookie, and in my city, it's really difficult to 'git clone' and 'conda install' directly, Network is not good, God, it's so tough to build image and run your code.
I'm Sorry that I Bother you because those stupid questions.

**Comment by tlin-taolin** [comment]
Hi, 

`open-jdk-7` is not needed and you can remove it if you want. But you need to build PyTorch from the source with CUDA-aware MPI support. The code uses MPI for master-worker communication.
