### ISSUE TITLE
About docker-compose

### ISSUE THREAD

**Issue by aqibsaeed** [epfml/federated-learning-public-code#5]
I built the docker container with the updated environment, but if I try starting the service as `docker-compose up` I get following error: 
`environments_base_1 exited with code 0` and `environments_pytorch-mpi_1 exited with code 0`. Am I missing something here? Could you please provide list of commands to properly start and run jobs within docker? Thanks.

**Comment by aqibsaeed** [comment]
Could you maybe please provide conda environment yml to install required packages? and installing pytorch from source with mpi support?

**Comment by aqibsaeed** [comment]
If I try installing one package at a time from the pytorch-mpi file I get the following error:
 ```
"4 errors detected in the compilation of "/home/my_user/vision/vision/vision/vision/pytorch/vision/torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1" 
```

when running: `git clone https://github.com/pytorch/vision.git && cd vision && git checkout tags/v0.9.2-rc2 && $HOME/conda/envs/pytorch-py$PYTHON_VERSION/bin/python setup.py install`

Any idea how to solve this ?

**Comment by tlin-taolin** [comment]
As mentioned in the readme, we use docker-compose to build the final image `user/pytorch-mpi` based on the dependency between images. To start the image, you can just use `docker run -it user/pytorch-mpi` here. Please also note that, you might need to add extra docker arguments here based on your own system configuration.

We also clearly stated some example scripts in the readme file.

If you decided to set up the environments without using docker, you can just extract the commands from the provided dockerfile yourself; but be careful with the potential broken package dependency...

**Comment by aqibsaeed** [comment]
Thank you!
